"""Generate src/data/products.js from product catalog metadata."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IMAGE_MAP = json.loads(
    (ROOT / "scripts" / "pptx_extract" / "image_map.json").read_text(encoding="utf-8")
)
# patch fixed images
IMAGE_MAP["k419"] = "k419.png"
IMAGE_MAP["d8100-plus"] = "d8100-plus.png"

CATEGORIES = """export const productCategories = [
  { id: 'all', title: '全部' },
  { id: 'pda', title: 'PDA 手持终端' },
  { id: 'tablet', title: '工业平板' },
  { id: 'wearable', title: '穿戴设备' },
  { id: 'rfid', title: 'RFID 设备' },
  { id: 'pos', title: 'POS 支付' },
  { id: 'scanner', title: '扫描设备' },
  { id: 'printer', title: '打印机' },
]
"""

PRODUCTS = [
    {
        "id": "dt630",
        "name": "DT630",
        "subtitle": "企业级智能手机 · 移动作业新基准",
        "category": "pda",
        "highlight": "Android 15 · 内置 UHF RFID · 5000 万像素 · 5G",
        "specs": [
            ("处理器", "8 核 2.5GHz · 独立 AI NPU"),
            ("系统", "Android 15（可升级至 Android 19）"),
            ("屏幕", "6.58 寸 1080×2408 · 170.5×78.1×10.4mm · 240g"),
            ("内存", "8+128GB · 最大 2TB SD"),
            ("RFID", "内置 UHF · 1.2m · ≥50 标签/秒 · Gen2X"),
            ("扫描", "后置专业扫描引擎 · 即扫即看 · 绿光瞄准"),
            ("防护", "IP68 · 1.5m 跌落（带套 1.8m）"),
            ("电池", "4500mAh 可拆卸"),
        ],
        "scenarios": [
            ("RFID 批量盘点", "内置 UHF 模块，仓库内 1.2 米批量识读，无需外接手柄。"),
            ("高端物流揽派", "5G + 专业扫描 + 高拍，揽收派件一单到底。"),
            ("医疗/政务移动作业", "NFC 读卡 + 高防护 + 长续航，适合户外移动核查。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "dt66",
        "name": "DT66",
        "subtitle": "6.5 寸企业级旗舰智能数据终端",
        "category": "pda",
        "highlight": "86.5% 屏占比 · 双 NFC · 可选 iToF · Wi-Fi 6E",
        "specs": [
            ("处理器", "八核 2.4GHz"),
            ("系统", "Android 13"),
            ("屏幕", "6.5 寸 · 175.8×76.5×14.5mm · 265g"),
            ("内存", "4+64GB / 6+128GB · 最大 256GB SD"),
            ("扫描", "专业扫描头 · 一维/二维 · 屏幕扫码"),
            ("通信", "5G 全网通 · Wi-Fi 6E · BT 5.2"),
            ("防护", "IP67 · 1.5m 抗跌落 · -20~60°C"),
            ("电池", "5000mAh 可拆卸 · 热插拔"),
        ],
        "scenarios": [
            ("仓储拣货", "大屏显示拣货清单，远距扫码减少弯腰，双 NFC 快速配对蓝牙打印机。"),
            ("门店盘点", "6.5 寸屏适合展示 SKU 详情，Wi-Fi 6E 保障实时库存同步。"),
            ("制造追溯", "工业防护 + 全天续航，产线报工与物料追溯稳定运行。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "dt50",
        "name": "DT50",
        "subtitle": "经典工业 PDA · 企业级智能数据终端",
        "category": "pda",
        "highlight": "5.7 寸 · IP67 · 5000mAh · Wi-Fi 6 Ready",
        "specs": [
            ("处理器", "八核 2.45GHz"),
            ("系统", "Android 11~13"),
            ("屏幕", "5.7 寸 HD+ 720×1440 · 162.6×76×13.6mm · 265g"),
            ("扫描", "标距/远距引擎 · 屏幕扫码 · PTT 对讲"),
            ("通信", "4G 全网通 · Wi-Fi 6 Ready · BT 5.0+"),
            ("防护", "IP67 · 1.5m 跌落"),
            ("电池", "5000mAh 可拆卸 · 热插拔"),
        ],
        "scenarios": [
            ("通用仓储", "成熟稳定，配件丰富，是仓储物流最常用型号之一。"),
            ("外勤巡检", "高清高亮大屏，室内外视野清晰，PTT 一键对讲。"),
            ("零售门店", "扫码 + 移动查询，门店库存与价签管理。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "dt50-5g",
        "name": "DT50 5G",
        "subtitle": "5G 企业级智能数据终端",
        "category": "pda",
        "highlight": "5G 全网通 · Android 12 · 可选 18W 快充 · IP67",
        "specs": [
            ("处理器", "八核 2.2GHz"),
            ("系统", "Android 12"),
            ("屏幕", "5.7 寸 720×1440 · 162.6×76×13.6mm"),
            ("内存", "4+64GB / 8+128GB"),
            ("通信", "5G/4G · Wi-Fi 双频 · BT 5.1 · NFC"),
            ("扫描", "专业扫描头 · 屏幕扫码 · PDAF 对焦"),
            ("防护", "IP67 · 1.5m 抗跌落"),
            ("电池", "5000mAh 可拆卸 · 可选 18W 快充"),
        ],
        "scenarios": [
            ("快递揽派", "5G 实时回传，毫秒级对焦拍照留证。"),
            ("智慧物流", "高带宽保障 WMS 实时同步，减少等待。"),
            ("户外作业", "超高亮度屏幕，强光下仍清晰可见。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "dt50-dp",
        "name": "DT50 DP",
        "subtitle": "工业级 DPM 安全智能终端",
        "category": "pda",
        "highlight": "专业 DPM 引擎 · 多光源照明 · Wi-Fi 6 Ready",
        "specs": [
            ("处理器", "八核 2.45GHz"),
            ("系统", "Android 11"),
            ("屏幕", "5.7 寸 720×1440 · 康宁玻璃"),
            ("扫描", "DPM 专用引擎 · 金属/曲面/低对比度码"),
            ("通信", "4G 双卡 · Wi-Fi 双频 · BT 5.0"),
            ("防护", "IP67 · 1.5m 抗跌落"),
            ("电池", "5000mAh 可拆卸"),
        ],
        "scenarios": [
            ("产线 DPM 追溯", "识读金属、曲面、低对比度 DPM 码，制造追溯必备。"),
            ("汽车零部件", "多光源多角度照明，适应复杂打标表面。"),
            ("航空航天", "高可靠工业防护，满足严苛产线环境。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "dt50-ex",
        "name": "DT50 Ex",
        "subtitle": "防爆智能终端",
        "category": "pda",
        "highlight": "Ex ib IIC T4 Gb · IP67 · 5000mAh · 头部 NFC",
        "specs": [
            ("处理器", "八核 2.45GHz"),
            ("系统", "Android 11"),
            ("屏幕", "5.7 寸全面屏 · 162.6×76×13.6mm"),
            ("防爆", "Ex ib IIC T4 Gb · 证号 CCRI 20.2301"),
            ("扫描", "专业一维/二维 · 屏幕扫码"),
            ("通信", "4G · Wi-Fi 6 Ready · BT 5.0 · NFC"),
            ("防护", "IP67 · 1.5m 抗跌落 · 康宁大猩猩玻璃"),
            ("电池", "5000mAh 可拆卸"),
        ],
        "scenarios": [
            ("危化/油气", "通过防爆认证，满足化工、油气等特种行业。"),
            ("制药洁净区", "防爆 + 工业防护，适应特殊监管环境。"),
            ("燃气巡检", "NFC 读卡 + 扫码，移动作业安全合规。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "dt50-5g-harmony",
        "name": "DT50 5G（鸿蒙版）",
        "subtitle": "开源鸿蒙 5G 智能终端",
        "category": "pda",
        "highlight": "OpenHarmony 5.0 · 国产八核 · 单北斗 · 纯国产化",
        "specs": [
            ("处理器", "国产八核 2.7GHz"),
            ("系统", "OpenHarmony 5.0"),
            ("屏幕", "5.7 寸 720×1440"),
            ("通信", "5G/4G · Wi-Fi 双频 · BT 5.0"),
            ("定位", "单北斗 · 抗干扰 · 保密性好"),
            ("扫描", "专业扫描头 · AI 算法 · 百万像素传感器"),
            ("防护", "IP67 · 1.5m 抗跌落"),
            ("电池", "5000mAh 可拆卸"),
        ],
        "scenarios": [
            ("政务/国企", "国产 OS + 纯国产化器件，满足信创要求。"),
            ("特种物流", "单北斗高精度定位，复杂环境稳定可用。"),
            ("公共安全", "安全可控操作系统，数据合规。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "dt50b",
        "name": "DT50B",
        "subtitle": "身份证硬解终端",
        "category": "pda",
        "highlight": "身份证硬解 · NFC · Wi-Fi 6 Ready · IP67",
        "specs": [
            ("处理器", "八核 2.45GHz"),
            ("系统", "Android 11~13"),
            ("屏幕", "5.7 寸 HD+"),
            ("身份证", "离线读二代证/港澳台居住证/外国人永居证"),
            ("通信", "4G · Wi-Fi 6 Ready · BT 5.0 · NFC"),
            ("扫描", "专业一维/二维"),
            ("防护", "IP67 · 1.5m 抗跌落"),
            ("电池", "5000mAh 可拆卸"),
        ],
        "scenarios": [
            ("政务办事", "离线读取身份证，高效精准录入。"),
            ("交通核验", "人证合一核验，文旅/交通多场景。"),
            ("酒店登记", "NFC + 身份证硬解，快速入住。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "rt30",
        "name": "RT30",
        "subtitle": "仓储物流内场专用手持终端",
        "category": "pda",
        "highlight": "3.5 寸 · ≥103dB 喇叭 · Android 14 · 人体工学握把",
        "specs": [
            ("处理器", "八核 2.0GHz"),
            ("系统", "Android 14"),
            ("屏幕", "3.5 寸 320×480 · 185×66.8×31.7mm · 240g"),
            ("按键", "26 键水晶键盘 + 3 扫描键"),
            ("音频", "≥103dB 大功率扬声器"),
            ("通信", "4G · Wi-Fi 双频漫游 · BT 5.0"),
            ("防护", "IP67 · 1.5m 跌落（带套 1.8m）"),
            ("电池", "4900mAh · 热插拔"),
        ],
        "scenarios": [
            ("快递分拣内场", "大音量播报 + 紧凑握把，嘈杂环境反馈清晰。"),
            ("仓库日常作业", "配置实用、久持不累，性价比之选。"),
            ("工厂线边仓", "工业防护 + 热插拔换电，保障班次连续作业。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "dt40",
        "name": "DT40",
        "subtitle": "工业级智能数据终端",
        "category": "pda",
        "highlight": "4 寸 · 21 键键盘 · DPM 可选 · IP67",
        "specs": [
            ("处理器", "八核 2.0GHz"),
            ("系统", "Android 11"),
            ("屏幕", "4 寸 480×800 · 164.5×68.6×17.5mm · 279g"),
            ("按键", "21 键数字键盘 + 双扫描键"),
            ("扫描", "专业引擎 · 一维/二维/DPM · 可选远距"),
            ("通信", "4G · Wi-Fi 双频 · BT 5.0 · 可选 NFC"),
            ("防护", "IP67 · 802.11r 漫游 <10ms"),
            ("电池", "4500mAh 可拆卸"),
        ],
        "scenarios": [
            ("制造产线", "数字键盘 + DPM 识读，产线报工高效。"),
            ("仓库拣货", "紧凑机身 + 大喇叭，嘈杂环境清晰反馈。"),
            ("资产盘点", "Wi-Fi 无缝漫游，移动盘点不断连。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "rt40s",
        "name": "RT40S",
        "subtitle": "远距扫描 · 全键盘工业终端",
        "category": "pda",
        "highlight": "可选 15m 超远距 · 冷链 -30°C · IP68 · 5200mAh",
        "specs": [
            ("处理器", "八核 2.45GHz"),
            ("系统", "Android 13"),
            ("屏幕/键盘", "4 寸 480×800 · 29/38/51 键全键盘"),
            ("扫描", "标准/远距扫描头 · 屏幕扫码 · 最远 15m"),
            ("通信", "4G 全网通 · Wi-Fi 6 · 2×2 MU-MIMO · BT 5.0"),
            ("防护", "IP68 · 1.8m 跌落"),
            ("工作温度", "常规 -20~50°C · 冷链 -30~50°C（自加热）"),
            ("电池", "5200mAh · 热插拔不换机"),
        ],
        "scenarios": [
            ("高位货架拣货", "15 米远距扫描，员工无需登梯或大幅弯腰。"),
            ("冷链仓储", "-30°C 冷链版，屏幕与扫描窗自加热，冷库作业不断档。"),
            ("物流分拣中心", "全键盘 + PTT 对讲，高强度分拣场景效率标杆。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "ct48",
        "name": "CT48",
        "subtitle": "轻巧工业级智能手持终端",
        "category": "pda",
        "highlight": "252g · 5000mAh · 25° 扫描视窗 · IP67",
        "specs": [
            ("处理器", "八核 2.0GHz"),
            ("系统", "Android 12"),
            ("屏幕", "4 寸 480×800 · 165.7×66×18mm · 252g"),
            ("音频", "1.5W 喇叭 · 10cm 处 ≥100dB"),
            ("扫描", "专业扫描头 · 25° 倾斜视窗 · 屏幕扫码"),
            ("通信", "4G · Wi-Fi 双频漫游 · BT 5.0 · 可选 NFC/eSIM"),
            ("防护", "IP67 · 1.5m 抗跌落"),
            ("电池", "5000mAh 可拆卸"),
        ],
        "scenarios": [
            ("快递揽收", "轻巧久握不累，大音量播报揽收结果。"),
            ("门店理货", "紧凑机身适合狭小货架间操作。"),
            ("外勤巡检", "全天续航 + 工业防护，户外稳定运行。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "ct58",
        "name": "CT58",
        "subtitle": "工业级智能手持终端",
        "category": "pda",
        "highlight": "5.7 寸 HD+ · PDAF · 25° 扫描视窗 · IP65",
        "specs": [
            ("处理器", "八核 2.45GHz"),
            ("系统", "Android 12"),
            ("屏幕", "5.7 寸 720×1440 · 162.6×76×13.6mm · 265g"),
            ("扫描", "专业引擎 · 一维/二维/扭曲/污损/屏幕码"),
            ("通信", "4G · Wi-Fi 双频漫游 · BT 5.0 · 可选 eSIM"),
            ("防护", "IP65 · 1.5m 抗跌落"),
            ("电池", "5000mAh 可拆卸"),
        ],
        "scenarios": [
            ("零售门店", "大屏 + 快速扫码，价签与库存管理。"),
            ("物流外场", "室外强光下高亮屏，PDAF 快速拍照。"),
            ("制造追溯", "25° 视窗人体工学，长时间扫码不累。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "dt510",
        "name": "DT510",
        "subtitle": "5G 智能数据终端 · 超值之选",
        "category": "pda",
        "highlight": "5G 全网通 · 5.5 寸 · AI 智能充电 · IP67",
        "specs": [
            ("处理器", "八核 2.2GHz"),
            ("系统", "Android 13"),
            ("屏幕", "5.5 寸 720×1440 · 161.6×73×16.8mm · 280g"),
            ("内存", "4+64GB / 8+128GB"),
            ("通信", "5G/4G · Wi-Fi 双频 · BT 5.2 · PTT 键"),
            ("防护", "IP67 · 1.5m 抗跌落 · -10~50°C"),
            ("电池", "5000mAh 可拆卸"),
        ],
        "scenarios": [
            ("中小物流网点", "5G 高速回传 + 合适价位，网点数字化入门首选。"),
            ("外勤巡检", "轻薄握感 + 全天续航，适合物业/设施巡检。"),
            ("零售门店管理", "扫码 + 移动查询，门店库存与价签管理。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "p8100p",
        "name": "P8100P",
        "subtitle": "10.1 寸工业平板电脑",
        "category": "tablet",
        "highlight": "10.1 寸 · 10000mAh · 专业扫描 · 4G/5G 可选",
        "specs": [
            ("处理器", "八核 2.45GHz（4G）/ 2.4GHz（5G）"),
            ("系统", "Android 13"),
            ("屏幕", "10.1 寸 1200×1920 · 255.4×175×18.5mm"),
            ("扫描", "专业一维/二维 · 污损/扭曲码"),
            ("通信", "4G/5G 双卡 · Wi-Fi 6/6E · BT 5.0/5.2"),
            ("防护", "IP65/IP67 · 1.2m 抗跌落"),
            ("电池", "10000mAh 可拆卸 · QC 快充"),
        ],
        "scenarios": [
            ("仓储叉车作业", "大屏展示 WMS 界面，座充/墙充灵活部署。"),
            ("制造产线", "平板 + 扫描一体化，工序指导与质检。"),
            ("户外巡检", "大电池 + 工业防护，全天移动作业。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "p8100",
        "name": "P8100",
        "subtitle": "8 寸工业平板电脑",
        "category": "tablet",
        "highlight": "8 寸 · Wi-Fi 6 Ready · 物理按键 · IP67",
        "specs": [
            ("处理器", "八核 2.45GHz"),
            ("系统", "Android 13"),
            ("屏幕", "8 寸高清 · 物理按键"),
            ("扫描", "专业引擎 · 一维/二维/污损/扭曲码"),
            ("通信", "Wi-Fi 6 Ready · 4G 可选"),
            ("音频", "双扬声器 BOX 音腔"),
            ("防护", "IP67 · 1.2m 抗跌落"),
        ],
        "scenarios": [
            ("门店管理", "8 寸屏 + 按键，店员操作更直观。"),
            ("Healthcare", "医疗护理移动站配套平板。"),
            ("固定工位", "墙充/支架部署，兼顾移动与固定场景。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "u2s",
        "name": "U2S",
        "subtitle": "穿戴式企业智能终端",
        "category": "wearable",
        "highlight": "4 寸 · Wi-Fi 6E · 3500mAh 热插拔 · IP65",
        "specs": [
            ("处理器", "八核 2.4GHz"),
            ("系统", "Android 14"),
            ("屏幕", "4 寸 480×800 · 118×91×18mm · 275g"),
            ("通信", "Wi-Fi 6E · 2×2 MU-MIMO · BT 5.3 · NFC"),
            ("防护", "IP65 · 1.5m 抗跌落"),
            ("电池", "3500mAh 可拆卸 · 热插拔"),
            ("摄像头", "前置 13MP · 双扬声器"),
        ],
        "scenarios": [
            ("仓储拣货", "腕带佩戴解放双手，扫码效率倍增。"),
            ("制造装配", "穿戴式终端 + SR5600 指环扫描。"),
            ("航空行李", "小巧便携，高强度流转场景。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "sr5600",
        "name": "SR5600",
        "subtitle": "蓝牙无线指环扫描器",
        "category": "scanner",
        "highlight": "75g · BT 5.3 · 80m 传输 · NFC 配对",
        "specs": [
            ("传感器", "1280×1080 CMOS · 60fps"),
            ("通信", "蓝牙 5.3 · 最远 80m · NFC 快速配对"),
            ("电池", "950mAh 可拆卸"),
            ("重量", "75g · 指环/挂绳/手套多种佩戴"),
            ("防护", "IP65 · 1.8m 抗跌落"),
            ("精度", "≥3mil · 360° 旋转识读"),
        ],
        "scenarios": [
            ("穿戴式作业", "配合 U2S 等终端，双手自由扫描。"),
            ("产线分拣", "指环佩戴，连续扫码不疲劳。"),
            ("零售盘点", "蓝牙连接手机/PAD，快速扩展扫描能力。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "dt50u",
        "name": "DT50U",
        "subtitle": "超高频 RFID 智能手持终端",
        "category": "rfid",
        "highlight": "20m+ 识读 · 1000+ 张/秒 · 9000mAh",
        "specs": [
            ("处理器", "八核 2.0GHz · Android 11"),
            ("RFID", "Impinj E710 · 5dBi 天线 · 20m+ · 1000+ 张/秒"),
            ("扫描", "专业一维/二维 · 屏幕扫码"),
            ("屏幕", "5.5 寸 · 678g"),
            ("通信", "4G 双卡 · Wi-Fi 双频 · BT 5.0"),
            ("防护", "IP67 · 1.2m 抗跌落"),
            ("电池", "9000mAh 大容量"),
        ],
        "scenarios": [
            ("服装仓储盘点", "批量识读货架标签，盘点时间缩短 90%。"),
            ("资产管理", "非视距批量清点固定资产，准确率 99%+。"),
            ("物流枢纽中转", "远距 + 群读，快速核验托盘/笼车 RFID 标签。"),
        ],
        "trainingPath": "/product/rfid",
    },
    {
        "id": "dt50u-lite",
        "name": "DT50U Lite",
        "subtitle": "轻便型 UHF RFID 手持终端",
        "category": "rfid",
        "highlight": "498g · 1300+ 张/秒 · 15m+ · 6500mAh",
        "specs": [
            ("处理器", "高通八核 2.45GHz · Android 13"),
            ("RFID", "Impinj E710 · Gen2X · 15m+ · 1300+ 张/秒"),
            ("重量", "498g（轻便握持）"),
            ("通信", "4G · Wi-Fi 6 Ready · 双频"),
            ("防护", "IP67 · 1.5m 抗跌落"),
            ("电池", "6500mAh 可拆卸"),
        ],
        "scenarios": [
            ("门店 RFID 盘点", "轻量化设计，店员长时间盘点不累手。"),
            ("图书馆/档案", "批量识读书架标签，非视距快速清点。"),
            ("医疗耗材管理", "高识读率 + 轻便，适合护士站耗材追溯。"),
        ],
        "trainingPath": "/product/rfid",
    },
    {
        "id": "dt50d",
        "name": "DT50D",
        "subtitle": "便携式 UHF RFID 手持终端",
        "category": "rfid",
        "highlight": "307g · 内置 UHF · 1.5m 批量识读 · IP67",
        "specs": [
            ("处理器", "八核 2.0GHz · Android 11"),
            ("RFID", "内置 UHF · 1.5m 批量识读"),
            ("屏幕", "5.5 寸 720×1440 · 307g"),
            ("扫描", "专业一维/二维 · 污损/扭曲码"),
            ("通信", "4G 双卡 · Wi-Fi 双频 · BT 5.0"),
            ("防护", "IP67 · 1.5m 抗跌落"),
            ("电池", "5000mAh 可拆卸"),
        ],
        "scenarios": [
            ("轻量 RFID 盘点", "内置 UHF 无需背夹，307g 轻装上阵。"),
            ("门店库存", "批量识读 + 条码单品追溯一机完成。"),
            ("资产管理", "非视距快速清点，灵活便携。"),
        ],
        "trainingPath": "/product/rfid",
    },
    {
        "id": "rfg91",
        "name": "RFG91",
        "subtitle": "超高频 RFID 手柄 · 条码+RFID 三合一",
        "category": "rfid",
        "highlight": "1300+ 张/秒 · 15m+ · 390g · 蓝牙扩展",
        "specs": [
            ("芯片", "Impinj E710 · Gen2X"),
            ("识读", "15m+ · 1300+ 张/秒 · 99.9% 准确率"),
            ("模式", "纯条码 / 纯 RFID / 条码+RFID 同时"),
            ("连接", "BT 5.0 · NFC 配对 · 兼容 Android/iOS/Windows"),
            ("电池", "5000mAh 可拆卸 · 可选 6700mAh"),
            ("重量", "390g · 手绳防滑"),
            ("防护", "IP67 · 1.5m 抗跌落"),
        ],
        "scenarios": [
            ("手机/PDA 扩展 RFID", "无需更换现有设备，手柄一键扩展为专业 RFID 终端。"),
            ("混合采集作业", "条码单品追溯 + RFID 批量盘点，一柄搞定。"),
            ("外场临时盘点", "蓝牙便携，快速配对现场任意移动设备。"),
        ],
        "trainingPath": "/product/rfid",
    },
    {
        "id": "fr1000",
        "name": "FR1000",
        "subtitle": "固定式超高频 RFID 读写器",
        "category": "rfid",
        "highlight": "1000+ 张/秒 · 8 天线 · PoE+ · Android 10",
        "specs": [
            ("处理器", "八核 1.6GHz · Android 10"),
            ("RFID", "1000+ 张/秒 · SJC 自适应对消"),
            ("天线", "8 个外接 SMA · 识读率提升 50%"),
            ("接口", "HDMI · RJ45 · RS232 · GPIO · 4G/Wi-Fi/BT"),
            ("供电", "PoE+ · 无需额外电源"),
            ("屏幕", "5.7 寸 · 180×128×28mm"),
        ],
        "scenarios": [
            ("仓储通道门", "多天线部署，托盘/笼车批量核验。"),
            ("产线工位", "固定读写，实时追踪在制品。"),
            ("物流枢纽", "PoE 灵活部署，减少布线成本。"),
        ],
        "trainingPath": "/product/rfid",
    },
    {
        "id": "fr2000",
        "name": "FR2000",
        "subtitle": "桌面式 RFID 读写器 · 零售结算",
        "category": "rfid",
        "highlight": "99.9% 识读 · 防窜读 · USB/PoE · 即插即用",
        "specs": [
            ("频率", "840~960MHz · ISO18000-6C"),
            ("功率", "0~30dBm 可调"),
            ("读距", "内置天线典型 <50cm"),
            ("接口", "Type-C USB · 蓝牙 5.0 · RJ45 · 可选 PoE"),
            ("尺寸", "325×325×20mm · 1850g"),
            ("防护", "IP54 · 金属外壳防信号外溢"),
        ],
        "scenarios": [
            ("RFID 自助收银", "优衣库模式，批量识读购物篮内 RFID 标签快速结算。"),
            ("门店试衣间", "桌面部署，实时读取试衣 RFID 标签，库存自动更新。"),
            ("珠宝/奢侈品", "精准识读小范围标签，金属环境防窜读设计。"),
        ],
        "trainingPath": "/product/rfid",
    },
    {
        "id": "fr7000",
        "name": "FR7000",
        "subtitle": "一体式超高频 RFID 读写器",
        "category": "rfid",
        "highlight": "1000 张/秒 · 6/9dBi · 7~12m 读距 · IP65",
        "specs": [
            ("芯片", "Impinj E710"),
            ("型号", "FR7600（6dBi）/ FR7900（9dBi）"),
            ("读距", "6dBi >7m · 9dBi >12m"),
            ("速率", "1000 张/秒 · 准确率 99.7%"),
            ("接口", "RS232 · RJ45 · 可选 RS485/韦根/GPIO/USB"),
            ("防护", "塑胶+铝合金 · 工业级防尘防水"),
        ],
        "scenarios": [
            ("仓库出入口", "一体式天线，安装便捷，馈线损耗低。"),
            ("产线传送带", "精准识读快速移动物品标签。"),
            ("停车场/门禁", "远距批量识读，灵活支架部署。"),
        ],
        "trainingPath": "/product/rfid",
    },
    {
        "id": "d81r",
        "name": "D81R 系列",
        "subtitle": "桌面式 RFID 打印机",
        "category": "printer",
        "highlight": "RFID 读写打印 · 203/300DPI · 智能校准",
        "specs": [
            ("打印", "热敏/热转印 · 203/300DPI · 最大 4inch/s"),
            ("RFID", "EPC Gen2/ISO18000-6C · 打印同时写入"),
            ("宽度", "D812R 104mm / D813R 108.4mm"),
            ("通讯", "USB 2.0 · 可选蓝牙/Wi-Fi"),
            ("校准", "一键校准 + 辅助工具 · 同规格免重复"),
            ("尺寸", "280×190×198mm · 2.7kg"),
        ],
        "scenarios": [
            ("RFID 标签发行", "打印+写入一体化，简化标签制作流程。"),
            ("资产管理", "精准追踪物品位置与状态。"),
            ("零售吊牌", "兼容多种 RFID 标签类型。"),
        ],
        "trainingPath": None,
    },
    {
        "id": "k329",
        "name": "K329",
        "subtitle": "移动便携打印机",
        "category": "printer",
        "highlight": "120mm/s · 双模蓝牙 · NFC · 72mm 宽",
        "specs": [
            ("打印", "热敏 · 203DPI · 最大 120mm/s"),
            ("宽度", "有效 72mm · 纸卷直径 50mm"),
            ("通讯", "USB Type-C · BT 2.1+4.2 · 可选 Wi-Fi 5GHz"),
            ("电池", "7.4V 2500mAh · 满电 1200~1300 张"),
            ("指令", "ESC/POS · CPCL · TSPL · 可选 ZPL"),
            ("尺寸", "118×105×62mm · 450g"),
        ],
        "scenarios": [
            ("移动揽收", "蓝牙连接 PDA，现场打印面单。"),
            ("餐饮外卖", "便携打印小票，双模蓝牙稳定连接。"),
            ("零售价签", "可视化 APP 编辑，无需二次开发。"),
        ],
        "trainingPath": None,
    },
    {
        "id": "k419",
        "name": "K419",
        "subtitle": "移动便携打印机",
        "category": "printer",
        "highlight": "90mm/s · 110mm 纸宽 · 56mm 大纸仓",
        "specs": [
            ("打印", "热敏 · 203DPI · 最大 90mm/s"),
            ("宽度", "有效 104mm · 纸卷直径 56mm"),
            ("通讯", "USB Type-C · BT 2.1+4.2"),
            ("电池", "11.1V 1600mAh"),
            ("指令", "ESC/POS · CPCL"),
            ("尺寸", "168×113×68mm · 507g"),
        ],
        "scenarios": [
            ("物流面单", "110mm 纸宽，大纸仓减少换纸。"),
            ("农贸市场", "便携打印交易凭证。"),
            ("仓储标签", "间隙/黑标检测，多尺寸标签。"),
        ],
        "trainingPath": None,
    },
    {
        "id": "d7100",
        "name": "D7100 系列",
        "subtitle": "热转印桌面打印机",
        "category": "printer",
        "highlight": "152mm/s · 120mm 纸宽 · 200/300DPI",
        "specs": [
            ("打印", "热转印 · 203DPI · 最大 125mm/s"),
            ("宽度", "20~120mm · 纸卷直径 67mm"),
            ("接口", "USB+串口+并口 · 可选网口/Wi-Fi/蓝牙"),
            ("传感器", "穿透式+反射式 · 精准测纸"),
            ("尺寸", "278×210×180mm · 2.3kg"),
        ],
        "scenarios": [
            ("仓储管理", "高速打印货位/托盘标签。"),
            ("医疗物流", "标签打印与追溯。"),
            ("零售制造", "分体式上盖，换纸便捷。"),
        ],
        "trainingPath": None,
    },
    {
        "id": "d8100-plus",
        "name": "D8100 Plus",
        "subtitle": "热转印桌面打印机",
        "category": "printer",
        "highlight": "203mm/s · TSPL/EPL/ZPL · 裁刀/剥纸器可选",
        "specs": [
            ("处理器", "400MHz ARM9 · 128MB SDRAM/Flash"),
            ("打印", "热转/热敏 · 203/300DPI · 最大 203mm/s"),
            ("宽度", "D8120 104mm / D8130 108.4mm"),
            ("接口", "USB · USB Host · 串口 · 网口 · 可选 Wi-Fi/BT"),
            ("功能", "可选裁刀/剥纸器 · 最小 5mm 标签"),
            ("尺寸", "280×190×198mm · 2.7kg"),
        ],
        "scenarios": [
            ("零售价签", "多指令兼容，对接现有系统。"),
            ("珠宝/医疗标签", "高精度小标签打印。"),
            ("服装吊牌", "高速打印 + 可选裁切。"),
        ],
        "trainingPath": None,
    },
    {
        "id": "d9100",
        "name": "D9100 Plus",
        "subtitle": "工业级打印机",
        "category": "printer",
        "highlight": "8 寸纸仓 · 450m 碳带 · 9.65kg 全金属",
        "specs": [
            ("处理器", "400MHz ARM9 · 128MB SDRAM/Flash"),
            ("打印", "热转/热敏 · 203/300DPI · 最大 203mm/s"),
            ("纸仓", "外径 8 寸 · 120mm 宽 · 450m 碳带"),
            ("接口", "USB Host · 网口 · 串口 · 可选 Wi-Fi/BT"),
            ("尺寸", "425×255×265mm · 9.65kg"),
            ("SDK", "Windows/Android SDK"),
        ],
        "scenarios": [
            ("包装赋码", "工业级连续打印，减少换纸损耗。"),
            ("零部件追溯", "大纸仓 + 长碳带，产线不停机。"),
            ("物流面单", "多指令仿真，对接 WMS/ERP。"),
        ],
        "trainingPath": None,
    },
    {
        "id": "k388-pro",
        "name": "K388 Pro",
        "subtitle": "移动智能贴标机",
        "category": "printer",
        "highlight": "扫打贴一体 · 1.5 秒/件 · Android 14 · 可选 RFID",
        "specs": [
            ("处理器", "八核 2.4GHz · Android 14"),
            ("屏幕", "5.5 寸 720×1440"),
            ("打印", "热敏 · 203DPI · 30~58mm · ≥120mm/s"),
            ("扫描", "一维/二维 · 扭曲/污损码"),
            ("模式", "一扫换标 / 扫多打一 / 扫一打多"),
            ("电池", "10.8V 3000mAh · 热插拔 · <800g"),
        ],
        "scenarios": [
            ("物流换标", "1.5 秒完成扫、打、贴，破损面单快速替换。"),
            ("仓储复核", "扫打贴一体，简化操作流程。"),
            ("零售价签", "移动贴标，随时更新货架标签。"),
        ],
        "trainingPath": None,
    },
    {
        "id": "i9000s",
        "name": "i9000S",
        "subtitle": "PDA-POS 二合一 · 智能移动 POS",
        "category": "pos",
        "highlight": "揽件+支付+打印 · 8 核 · 5000mAh · 全支付受理",
        "specs": [
            ("处理器", "八核 2.0GHz · Android 13"),
            ("屏幕", "5.0 寸 720×1280 · 184×81×51mm · 521g"),
            ("支付", "磁条/IC/非接/NFC/扫码 · PCI/EMV 认证"),
            ("打印", "58mm 热敏 · 纸卷直径 30mm"),
            ("扫描", "摄像头扫码 · 可选专业 2D 顶扫"),
            ("通信", "4G · Wi-Fi 双频 · BT 5.0 · GPS/北斗"),
            ("电池", "5000mAh · 可选 -10°C 低温电池"),
        ],
        "scenarios": [
            ("快递揽件", "扫码 + 打印面单 + 收款，一单到底不换设备。"),
            ("交警/停车执法", "移动执法开单、打印、支付一体化。"),
            ("移动零售收银", "展会/快闪店/外卖骑手，随身收银打印。"),
        ],
        "trainingPath": "/product/pos",
    },
    {
        "id": "i9200",
        "name": "i9200",
        "subtitle": "轻薄智能移动终端 · 非金/金融可选",
        "category": "pos",
        "highlight": "5.5 寸 · 400g · 58mm 打印 · 双模打印",
        "specs": [
            ("处理器", "四核 2.0GHz · Android 13"),
            ("屏幕", "5.5 寸 720×1440 · 205×78×63mm · 400g"),
            ("内存", "3+32GB · 多卡槽扩展"),
            ("打印", "58mm 热敏 · 票据/标签双模切换"),
            ("扫描", "摄像头扫码 · 可选专业扫描引擎"),
            ("通信", "4G · BT 5.0 · Wi-Fi 双频 · 可选 NFC/eSIM"),
        ],
        "scenarios": [
            ("便利店/餐饮", "非金版性价比最高，扫码收银 + 小票打印。"),
            ("菜市场/摊贩", "轻薄便携，支持多种支付方式聚合。"),
            ("移动点单", "餐饮服务员随身点单、厨打、结账。"),
        ],
        "trainingPath": "/product/pos",
    },
    {
        "id": "q1500",
        "name": "Q1500",
        "subtitle": "4G 云音箱 · 支付语音播报",
        "category": "pos",
        "highlight": "TTS 播报 · 4G Cat1 · Wi-Fi · 2000mAh",
        "specs": [
            ("通信", "4G Cat1 · Wi-Fi"),
            ("音频", "4Ω 3W 喇叭 · 专业录音/TTS 播报"),
            ("按键", "电源 · 音量 +/- · 功能键（重播/复位）"),
            ("电池", "3.7V 2000mAh · Type-C 充电"),
            ("认证", "CCC · SRRC · CTA"),
            ("工作温度", "-10~50°C"),
        ],
        "scenarios": [
            ("小商户收款", "微信/支付宝到账实时播报，防止逃单。"),
            ("农贸集市", "4G 无需宽带，摆摊即可语音播报。"),
            ("快递驿站", "到件/取件通知播报，提升驿站服务体验。"),
        ],
        "trainingPath": "/product/pos",
    },
    {
        "id": "q200",
        "name": "Q200",
        "subtitle": "台式扫描盒 · 高效收银",
        "category": "scanner",
        "highlight": "360° 扫码 · 自动感应 · 270g · 1.5m 跌落",
        "specs": [
            ("摄像头", "640×480 CMOS · 30fps"),
            ("视角", "水平 53° · 垂直 41° · 360° 旋转"),
            ("接口", "USB-HID · 虚拟串口 · HID-KBW"),
            ("兼容", "Windows / Android / Linux"),
            ("重量", "270g · 1.5m 线长"),
            ("防护", "1.5m 抗跌落 · -20~60°C"),
        ],
        "scenarios": [
            ("零售收银", "大扫描窗口，支付码/券码即插即用。"),
            ("餐饮前台", "自动感应，360° 识读。"),
            ("自助结算", "桌面部署，语音播报交易结果。"),
        ],
        "trainingPath": "/product/pos",
    },
    {
        "id": "k200",
        "name": "K200",
        "subtitle": "CODEK 有线工业扫描枪 · DPM 专用",
        "category": "scanner",
        "highlight": "DPM 码 · IP54 · 1.8m 跌落 · ≥3mil 精度",
        "specs": [
            ("传感器", "130 万像素 CMOS · 60 帧/秒"),
            ("照明", "暖白 + 红色双 LED"),
            ("接口", "USB · RS232 · USB-HID/虚拟串口"),
            ("识读", "DPM/一维/二维 · 360° · ±60°"),
            ("防护", "IP54 · 1.8m 抗跌落"),
            ("提示", "蜂鸣 + LED + 振动三重反馈"),
            ("兼容", "Windows / Android / Linux"),
        ],
        "scenarios": [
            ("产线 DPM 追溯", "识读金属/曲面/低对比度 DPM 码，制造追溯必备。"),
            ("固定工位扫描", "有线即插即用，适合流水线固定扫描位。"),
            ("PC 端入库", "配合 WMS 桌面端，高速扫码入库。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "k220",
        "name": "K220",
        "subtitle": "无线工业扫描枪",
        "category": "scanner",
        "highlight": "3200mAh · 25h 续航 · BT 5.0 · 100m 传输",
        "specs": [
            ("电池", "3200mAh · 连续工作 25 小时"),
            ("扫描", "满电约 4 万次 · BT 5.0 无线"),
            ("距离", "100m 空旷环境传输"),
            ("防护", "工业级抗跌落"),
        ],
        "scenarios": [
            ("仓储远距", "无线自由移动，高位货架无需拖线。"),
            ("产线巡检", "长续航保障整班连续作业。"),
            ("零售后台", "100m 覆盖，仓库到前台不断连。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "s716",
        "name": "S716",
        "subtitle": "无线扫描枪",
        "category": "scanner",
        "highlight": "BT 4.2 + 2.4G · 2200mAh · 160g",
        "specs": [
            ("传感器", "640×480 CMOS"),
            ("连接", "USB · 蓝牙 4.2 · 2.4G 无线"),
            ("模式", "手动/自动感应 · 震动+蜂鸣+LED"),
            ("电池", "2200mAh · USB 充电"),
            ("尺寸", "138×101×63mm · 160g"),
            ("兼容", "Windows / Android / Linux"),
        ],
        "scenarios": [
            ("零售收银", "双模无线，灵活切换连接方式。"),
            ("仓库盘点", "自动感应模式，连续扫码效率高。"),
            ("移动办公", "轻量 160g，长时间使用不累。"),
        ],
        "trainingPath": "/product/pda",
    },
    {
        "id": "s710",
        "name": "S710",
        "subtitle": "有线扫描枪",
        "category": "scanner",
        "highlight": "USB-HID · 360° 识读 · 185g · 1.8m 线",
        "specs": [
            ("传感器", "640×480 CMOS · 水平 31°"),
            ("接口", "USB-HID · 虚拟串口 · HID-KBW"),
            ("识读", "一维/二维 · 支付码/券码/彩色码"),
            ("重量", "185g（含线）· 110×71×158mm"),
            ("防护", "1.5m 抗跌落 · -20~60°C"),
            ("兼容", "Windows / Android / Linux"),
        ],
        "scenarios": [
            ("商超收银", "即插即用，快速读取支付码。"),
            ("仓储管理", "有线稳定，适合固定工位。"),
            ("快速物流", "360° 识读，操作角度灵活。"),
        ],
        "trainingPath": "/product/pda",
    },
]


def js_str(s):
    return json.dumps(s, ensure_ascii=False)


def render_product(p):
    img_file = IMAGE_MAP.get(p["id"])
    if not img_file:
        img_file = f"{p['id']}.png"
    lines = [
        "  {",
        f"    id: {js_str(p['id'])},",
        f"    name: {js_str(p['name'])},",
        f"    subtitle: {js_str(p['subtitle'])},",
        f"    category: {js_str(p['category'])},",
        f"    image: `${{import.meta.env.BASE_URL}}products/{img_file}`,",
        f"    highlight: {js_str(p['highlight'])},",
        "    specs: [",
    ]
    for label, value in p["specs"]:
        lines.append(f"      {{ label: {js_str(label)}, value: {js_str(value)} }},")
    lines.append("    ],")
    lines.append("    scenarios: [")
    for title, desc in p["scenarios"]:
        lines.append(f"      {{ title: {js_str(title)}, desc: {js_str(desc)} }},")
    lines.append("    ],")
    if p.get("trainingPath"):
        lines.append(f"    trainingPath: {js_str(p['trainingPath'])},")
    lines.append("  },")
    return "\n".join(lines)


header = """/**
 * 产品图鉴 - 单品数据（图片 / 参数 / 场景）
 * 数据来源：优博讯全系列产品介绍 PPT（20260131）
 */

"""

footer = """
export function getProductById(id) {
  return productCatalog.find((p) => p.id === id)
}

export function getCategoryTitle(id) {
  return productCategories.find((c) => c.id === id)?.title || id
}
"""

body = "export const productCatalog = [\n" + "\n".join(render_product(p) for p in PRODUCTS) + "\n]\n"
out = header + CATEGORIES + "\n" + body + footer
(ROOT / "src" / "data" / "products.js").write_text(out, encoding="utf-8")
print(f"Generated {len(PRODUCTS)} products -> src/data/products.js")
